### ISSUE TITLE
hy bro

### ISSUE THREAD

**Issue by mrmsdv** [KANG-NEWBIE/s-mbf#1]
cuy .. we mr_msdv
[1] btw itu kenapa ga di buat langsung auto login aja di awal setelah bannernya.. 
supaya ga harus login ulang" 
jadi ketika sudah login tinggal choice saja
[2] dan pada bagian dump id grup itu .. limit dari facebook adalah 5000 
     kalau lu mau kasih limit jangan di situ tapi di bagian readlines saja 
     dan klo lu mau , bisa kasih fugsi perulangan untuk dump id membernya

**Comment by sinoobie** [comment]
Malah kalo login di taru di awal nanti loginnya berulang" kaya mbf punyanya bg pirman

Terimakasih atas masukannya gan:)

**Comment by mrmsdv** [comment]
klo gitu buat seperti OSIF
dengan membaca keberadaan acces token
dan kalau accetoken tidak ada barulah dia di paksa untuk login


Pada tanggal Sen, 11 Mar 2019 pukul 17.43 NOOBIE <notifications@github.com>
menulis:
